sudo: required
dist: trusty
language: java
jdk:
- openjdk10
branches:
  only:
  - develop
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: 0WMB4R8Vg/+YkcDAseyjOIyYCZFDTvyCyJFob7z5OFsBtsdCN1HiApJJQwQ67xpcQauBfBRY9NoLnwcSWoH6qG7ZM72GS2q+NQDswYV9qrV/uKOlYmrLLEKtLZRe4Bc9JHi1o0DX9nr7UkltlNMRJI5y4HAQFR/MqDX2L6OQnXdF+8v/5HBt8TPwof6jX6xLkRgBlCw1u/fmW2tiVd6YYHgo0suJeKAyRWaCwOoXol9Ap/Xa9cUosGM96R9UcuWIc9tx5jg1CyLogt7dWZFDYt5lY/y8ni9L1qWc0nB/qplG1D9rlb0RCgOo8mmf6WgiAxNKv9X6e2GxRQx6JkoRBcOFWIRwZgODHJAwgBl0BzOyZ1KRzRdeBrzuSmo7EwEcweKiAj5bVrQ6wlNy8nlJaa3tmgEZJ3asmDzJjl3YtNntnDRliKWft4uChJ5WVnIpK4O9g3jHLf2XKIX2byK0S9xfD0pyjoTlRUgDMi84NljMhGlVniYWLfKfBUAG4Gild5REVHC7ZZAmd9b5HnO4GLu2uZId33Y+//tJDpAssV6gLEWa0Hh9n+9CCSoO/NFCgdN5IZn8vg15O3DRdfCuy91hP7qZVQVJ8hi0fwztJpUcnZRBGAU7wwfZf6WzxFDav2UJlQIWyfZmx5MpoJbuT3pogQZJi5LWmMYKErZuE2M=
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml'
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml'
env:
  global:
  - secure: RQzEjQw1+AOOte+KDc0vSP7auV6d+iCSEuIu3toniJ0SDHFEkFj/VvWJA+MbyfIGIwvpgBY2kzk8MUrvutEOSwdl1jTAGJ6vPzN1OPCWMKoo8KnxKwGhlAz3wJDOFDDzXQse+HCSQACsLDRbS9fMknMORI/QFwcXuTL132xrZbJ2eRt9oVZxkeGQCXPapMs9/Xi2d8vs6fQjyfFBQfEtRrXfQtME+bJvPSslkRSN7zqVFr73Nq+iLzQ5cnzjPAcqmIvIJMwIMxW0hYfZDMYt7UcreFHecC6cP9qPUIH1qkWVGMEnfU6C4/P4OCFjFYEggmSEQINtGrjipC7QX7sUtwaaCRYGo/YHZjid+C+GRs07GPPxy0ZvbxMg1Pd4sOUahtmks4r69Eb+Gltz3jXxmuuWQHLaB/+lalWkAPM3AqzE3kiCrVYdTfxo49axWOeD2PaGJnksYTTfwv49Foo8r4SgvuWHtxQAgKtY8eYO384YlS5s378SMJGPkxdJEVXspTPPUpbXytzz6gx+b6FgCCKCNcPYKQnetbFLbtiAHiee2fsarHQBqI8juznKCExGfmA70bI0uBzfBhqEQjHGzAq0iak9PYAKjfcJRpAzp7Ini/3Z7BEx1+w5ZCN2B8w5SxG8tcVY/KAfLTcAJtIbUiaGnpT2ehP4iGYRvYRVVPo=
  - secure: NG7tuc1+UnKCbJHCT8NI6wuLWQ2UIPJmj8g4n4zg5hOiFv9rFrQW2JGabx2jtq7qfAUgwoA1cUqpchFxd7fapUs+Y/W7Ui60QtEuQ1x9rP15xHDZVinKBD4SSlF4fsbu8DnW5Vy9Ao6c/a6fh962tZvnbieVuY+u/D3vFPfFW2a7tasfzXAUtaw+R34jxf8ytfpsCZzBYK3o1i4f0LHZ442UpKWG/bXxSWiTxociO7ARZdBtBWy4WrScyPkCBfIsgomuB13kXPURHohfTZKhMerD1XHH/ePY0sMfeCsTKANpDpl+A/mGA5Y3jffTjRnex4zd6N2YAxsIixw6WhC8zHEUy7Us9AeI3VB0ei80QZw74OgWDRdtt5tO+bznBS4kByxBF6XpFMTQz85y41LWoCTW14i7uGAh7x85c0l4qTpy6HHwEihW+sQ28hGKSok8YXyL7RHDd/KeV8+xQObzHMYIFaXWs359TnhrLE0D0Wr+2E7VD4Toms8NpT9uPHzCSyhJpFv1hpch7Yvn7iJGKwYc4tZNBsqV7xlghnV4PBTafk/mTIcvjAyyYht84km062Wv4KVftXYVw0i6zlgbVKmXWGs70EKDj2FkUvr8khU+GOT0hs+0UMsES4Sd6QBfT7Uwf5Mn/GQWV2vVSktEZ9sITinbzBS+oLe2nRNIeNg=
